### PR TITLE
French Translations

### PR DESCRIPTION
**Pull request by Revo78**

### CODE REVIEW

**Comment by yukihito23** [comment]
@Revo78 do you mind us adding you as contributor for the project if/when these French translations go in to production?

**Comment by Revo78** [comment]
@yukihito23 I don't mind it, you can go for it. I will keep the French translations updated.

**Comment by yukihito23** [comment]
@Revo78 thanks!

**Comment by yukihito23** [comment]
@Revo78 your French translations has been merged and in v0.97 we have released today.
Your name has been added to the CHR monument listed under Contributors if you are curious.

Thanks again for your contribution!

**Pull request merged**
